In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('divorce_df.csv')

In [5]:
df.head()

age_at_marriage  marriage_duration_years  num_children  \
0               30                        1             1   
1               27                        2             2   
2               31                        6             0   
3               35                        3             2   
4               26                        2             2   

       education_level employment_status  combined_income  \
0             Bachelor         Full-time            64001   
1               Master         Full-time            86221   
2          High School         Part-time            69441   
3             Bachelor         Full-time            69513   
4  No Formal Education         Full-time            63986   

  religious_compatibility  cultural_background_match  communication_score  \
0      Different Religion                          1             5.536016   
1           Same Religion                          1             5.810172   
2           Same Religion                          0             6.088146   
3           Not Religious                          1             6.212046   
4      Different Religion                          1             4.826262   

   conflict_frequency  ... mental_health_issues  infidelity_occurred  \
0                   3  ...                    0                    0   
1                   3  ...                    0                    1   
2                   3  ...                    0                    0   
3                   3  ...                    0                    0   
4                   1  ...                    0                    0   

   counseling_attended  social_support  shared_hobbies_count  marriage_type  \
0                    0        8.428183                     5           Love   
1                    0        5.297221                     1           Love   
2                    0        5.887066                     1       Arranged   
3                    0        5.263555                     5           Love   
4                    1        5.771259                     4           Love   

   pre_marital_cohabitation domestic_violence_history  trust_score  divorced  
0                         1                         0     6.262411         1  
1                         1                         0     6.769384         1  
2                         1                         0     5.532866         1  
3                         1                         0     3.491264         0  
4                         1                         0    10.000000         1  

[5 rows x 22 columns]

In [6]:
df.isnull().sum()

age_at_marriage              0
marriage_duration_years      0
num_children                 0
education_level              0
employment_status            0
combined_income              0
religious_compatibility      0
cultural_background_match    0
communication_score          0
conflict_frequency           0
conflict_resolution_style    0
financial_stress_level       0
mental_health_issues         0
infidelity_occurred          0
counseling_attended          0
social_support               0
shared_hobbies_count         0
marriage_type                0
pre_marital_cohabitation     0
domestic_violence_history    0
trust_score                  0
divorced                     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   age_at_marriage            5000 non-null   int64  
 1   marriage_duration_years    5000 non-null   int64  
 2   num_children               5000 non-null   int64  
 3   education_level            5000 non-null   object 
 4   employment_status          5000 non-null   object 
 5   combined_income            5000 non-null   int64  
 6   religious_compatibility    5000 non-null   object 
 7   cultural_background_match  5000 non-null   int64  
 8   communication_score        5000 non-null   float64
 9   conflict_frequency         5000 non-null   int64  
 10  conflict_resolution_style  5000 non-null   object 
 11  financial_stress_level     5000 non-null   float64
 12  mental_health_issues       5000 non-null   int64  
 13  infidelity_occurred        5000 non-null   int64

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
col = ['education_level','employment_status','religious_compatibility','conflict_resolution_style','marriage_type']
for i in col:
    df[i] = le.fit_transform(df[i])


In [14]:
df.head()

age_at_marriage  marriage_duration_years  num_children  education_level  \
0               30                        1             1                0   
1               27                        2             2                2   
2               31                        6             0                1   
3               35                        3             2                0   
4               26                        2             2                3   

   employment_status  combined_income  religious_compatibility  \
0                  0            64001                        0   
1                  0            86221                        2   
2                  2            69441                        2   
3                  0            69513                        1   
4                  0            63986                        0   

   cultural_background_match  communication_score  conflict_frequency  ...  \
0                          1             5.536016                   3  ...   
1                          1             5.810172                   3  ...   
2                          0             6.088146                   3  ...   
3                          1             6.212046                   3  ...   
4                          1             4.826262                   1  ...   

   mental_health_issues  infidelity_occurred  counseling_attended  \
0                     0                    0                    0   
1                     0                    1                    0   
2                     0                    0                    0   
3                     0                    0                    0   
4                     0                    0                    1   

   social_support  shared_hobbies_count  marriage_type  \
0        8.428183                     5              1   
1        5.297221                     1              1   
2        5.887066                     1              0   
3        5.263555                     5              1   
4        5.771259                     4              1   

   pre_marital_cohabitation  domestic_violence_history  trust_score  divorced  
0                         1                          0     6.262411         1  
1                         1                          0     6.769384         1  
2                         1                          0     5.532866         1  
3                         1                          0     3.491264         0  
4                         1                          0    10.000000         1  

[5 rows x 22 columns]

In [15]:
X = df.drop('divorced',axis=1)
y = df['divorced']

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 42)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
def evaluate(model, X_train, y_train, X_test, y_test):

    # Predictions
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    # Probabilities (needed for ROC-AUC)
    train_prob = model.predict_proba(X_train)[:, 1]
    test_prob = model.predict_proba(X_test)[:, 1]

    print(f"Evaluation for {model}")
    print("-" * 50)

    # Accuracy
    print(f"Training Accuracy for {model} is {accuracy_score(y_train, train_pred)}")
    print(f"Testing Accuracy for {model} is {accuracy_score(y_test, test_pred)}")

    print("\nConfusion Matrix (Test):")
    print(confusion_matrix(y_test, test_pred))

    print("\nClassification Report (Test):")
    print(classification_report(y_test, test_pred))

    # ROC-AUC
    print(f"Training ROC-AUC for {model} is {roc_auc_score(y_train, train_prob)}")
    print(f"Testing ROC-AUC for {model} is {roc_auc_score(y_test, test_prob)}")

In [22]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [28]:
evaluate(lr,X_train,y_train,X_test,y_test)

Evaluation for LogisticRegression()
--------------------------------------------------
Training Accuracy for LogisticRegression() is 0.614
Testing Accuracy for LogisticRegression() is 0.612

Confusion Matrix (Test):
[[538  55]
 [333  74]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.62      0.91      0.73       593
           1       0.57      0.18      0.28       407

    accuracy                           0.61      1000
   macro avg       0.60      0.54      0.51      1000
weighted avg       0.60      0.61      0.55      1000

Training ROC-AUC for LogisticRegression() is 0.5979434243093183
Testing ROC-AUC for LogisticRegression() is 0.6032210349242391


In [31]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(X_train,y_train)

KNeighborsClassifier()

In [33]:
evaluate(kn,X_train,y_train,X_test,y_test)

Evaluation for KNeighborsClassifier()
--------------------------------------------------
Training Accuracy for KNeighborsClassifier() is 0.72125
Testing Accuracy for KNeighborsClassifier() is 0.542

Confusion Matrix (Test):
[[424 169]
 [289 118]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.59      0.72      0.65       593
           1       0.41      0.29      0.34       407

    accuracy                           0.54      1000
   macro avg       0.50      0.50      0.49      1000
weighted avg       0.52      0.54      0.52      1000

Training ROC-AUC for KNeighborsClassifier() is 0.7725576857147636
Testing ROC-AUC for KNeighborsClassifier() is 0.5153013660602194


In [36]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=42
)

dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, min_samples_split=20,
                       random_state=42)

In [37]:
evaluate(dt,X_train,y_train,X_test,y_test)


Evaluation for DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, min_samples_split=20,
                       random_state=42)
--------------------------------------------------
Training Accuracy for DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, min_samples_split=20,
                       random_state=42) is 0.633
Testing Accuracy for DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, min_samples_split=20,
                       random_state=42) is 0.613

Confusion Matrix (Test):
[[521  72]
 [315  92]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.62      0.88      0.73       593
           1       0.56      0.23      0.32       407

    accuracy                           0.61      1000
   macro avg       0.59      0.55      0.53      1000
weighted avg       0.60      0.61      0.56      1000

Training ROC-AUC for DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, min_samples_split=20,
         

In [42]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=6,
    min_samples_split=30,
    min_samples_leaf=15,
    max_features="sqrt",
    class_weight="balanced_subsample",
    random_state=42

    )
rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced_subsample', max_depth=6,
                       min_samples_leaf=15, min_samples_split=30,
                       n_estimators=400, random_state=42)

In [43]:
evaluate(rf,X_train,y_train,X_test,y_test)


Evaluation for RandomForestClassifier(class_weight='balanced_subsample', max_depth=6,
                       min_samples_leaf=15, min_samples_split=30,
                       n_estimators=400, random_state=42)
--------------------------------------------------
Training Accuracy for RandomForestClassifier(class_weight='balanced_subsample', max_depth=6,
                       min_samples_leaf=15, min_samples_split=30,
                       n_estimators=400, random_state=42) is 0.689
Testing Accuracy for RandomForestClassifier(class_weight='balanced_subsample', max_depth=6,
                       min_samples_leaf=15, min_samples_split=30,
                       n_estimators=400, random_state=42) is 0.565

Confusion Matrix (Test):
[[354 239]
 [196 211]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.64      0.60      0.62       593
           1       0.47      0.52      0.49       407

    accuracy                           0.56 

In [44]:
import pickle

with open("divorce_model.pkl", "wb") as fs :
    pickle.dump(rf,fs)
